export interface AppointmentElement{
    FirstName:string;
MiddleName:string;
LastName:string;
Sex:string;
BirthDate:string;
EmailAddress:string;
Nationality:string;
Region:string;
City:string;
Subcity:string;
Woreda:string;
MobileNumber:string;
TestCenter:string;
TestReason:string;
PaymentMethod:string;
PassportNumber:string;
Passportexdate:string;
TravelDate:string;
TicketNumber:string;
DestinationCountry:string;
TestDate:string;
TestTime:string;
Remark:string;
}